package com.guochao.faceshow.utils;

import androidx.collection.ArraySet;
import java.util.Set;
/* loaded from: classes4.dex */
public class BaseConfig {
    public static final String API_DOMAIN_NAME = "dhcxzil.facecast.xyz";
    public static final String APP_ID = "wxd2a73493abdc882d";
    public static final String APP_KEY = "41e26c6f170242ab6f1b5672f52df79a";
    public static final String APP_PACKAGE_FILE_PROVIDERE = "com.guochao.faceshow.fileprovider";
    public static final String AREA_TYPE = "area_type";
    public static final String AUDIENCEINFORMATIONS = "audienceInformations";
    public static final int BIND_EMAIL_RESULT_CODE = 1005;
    public static final int BIND_MOBILE = 0;
    public static final int BIND_MOBILE_CHANGE = 1;
    public static final boolean CHINESE = false;
    public static final int DATE_SET_PERMISSIONS_CODE = 1011;
    public static final String DB_TYPE_COMPREEHNSIVE_NAME = "comprehensive";
    public static final String DB_TYPE_MUSIC_NAME = "music";
    public static final String DB_TYPE_PLACE_NAME = "place";
    public static final String DB_TYPE_TOPIC_NAME = "topic";
    public static final String DB_TYPE_USER_NAME = "USER";
    public static final int DRESS_UP_ITEM_CONTENT = 1089;
    public static final int DRESS_UP_TITLE = 1088;
    public static final String EMAIL_MATCHES = "^[A-Za-z0-9\\u4e00-\\u9fa5]+@[a-zA-Z0-9_-]+(\\.[a-zA-Z0-9_-]+)+$";
    public static final int FCM_PUSH_BUZID = 6974;
    public static final String FILE_DOMAIN_NAME = "mp4.facecast.xyz";
    public static final int HAS_ONE_VIEW = 0;
    public static final int HW_PUSH_BUZID = 11819;
    public static final int IM_SDK_APPID = 1400088004;
    public static final String INTENT_EXTRA_KEY_QR_SCAN = "intent_extra_key_qr_scan";
    public static final int INTERESTS_HOBBIES_ONE = 1111;
    public static final int INTERESTS_HOBBIES_THREE = 3333;
    public static final int INTERESTS_HOBBIES_TWO = 2222;
    public static final String IS_FIST_CHECK_GIF = "is_fist_check_gif";
    public static final String ITEM = "item";
    public static final String ITEM_POSITION = "item_position";
    public static final String ITEM_RIGHT = "item_right";
    public static final String KEY_24_48_SEND_HELLO_GIFT_ID = "KEY_24_48_SEND_HELLO_GIFT_ID";
    public static final String KEY_CURRENT_SUMMON = "key_current_summon";
    public static final String KEY_GUILD_EXPIRE_DAY = "guild_expire_day";
    public static final String KEY_HELLO_ANCHOR_SWITCH = "key_hello_anchor_switch";
    public static final String KEY_HELLO_STAR = "key_hello_star";
    public static final String KEY_SEND_HELLO_GIFT_ID = "KEY_SEND_HELLO_GIFT_ID";
    public static final String KEY_THANK_HELLO_GIFT_USER = "key_thank_hello_gift_user";
    public static final String KEY_TOKEN = "systoken";
    public static final String LIVEROOMMODEL = "mLiveRoomModel";
    public static final String LIVE_APPLY_CONVERSATION_SATE = "live_apply_linmark_sate";
    public static final String LIVE_DOMAIN_NAME = "live.facecast.xyz";
    public static final String LIVE_DOMAIN_NAME_ALIAS = "live.facecast.xyz.tlivecdn.com";
    public static final String MZ_PUSH_APPID = "1003023";
    public static final String MZ_PUSH_APPKEY = "fd5957a668b9473491f5a72e21f8bef5";
    public static final int MZ_PUSH_BUZID = 4690;
    public static final int NONE_BG_VIEW = 2;
    public static final int NONE_STICKY_GRID_VIEW = 3;
    public static final int NONE_STICKY_LINEAR_VIEW = 1;
    public static final String PEOPLE_NEARBY_ITEM = "people_nearby_item";
    public static final String PUSH_DOMAIN_NAME = "push.facecast.xyz";
    public static final String PUSH_DOMAIN_NAME_ALIAS = "push.facecast.xyz.tlivepush.com";
    public static final String QQ_ID = "1106758359";
    public static final int REAL_NAME_RESTART = 10021;
    public static final String RECOMMENDED_ITEM = "recommended_item";
    public static final int RELATE_USER_USER_CODE = 1006;
    public static final int REQUEST_CODE_IMAGE = 10023;
    public static final int REQUEST_COUNTRY = 99;
    public static final String RESUlT_FIND_FRIEND_SETTING = "result_find_friendsetting";
    public static final int RESUlT_FIND_FRIEND_SETTING_CODE = 1007;
    public static final String RESUlT_FIND_LANGUAGE = "result_language";
    public static final int RESUlT_FIND_LANGYAGE = 1003;
    public static final String RESUlT_FIND_RESIDENCE = "result_residence";
    public static final int RESUlT_FIND_RESIDENCE_CODE = 1004;
    public static final int RESUlT_PEOPLE_NEARBY_CODE = 1002;
    public static final int RESUlT_SCAN_CODE = 1001;
    public static final String SP_CONTANCTS_CIRCLE_EXPLORE = "sp_contancts_circle_explore";
    public static final String SP_CONTANCTS_CIRCLE_VISIBILITY = "sp_contancts_circle_visibility";
    public static final String SP_CONTANCTS_RED_POINT = "sp_contancts_red_point";
    public static final String SP_FRIEND_RELATION = "sp_friend_relation";
    public static final String SP_IS_FIRST_LIVE = "sp_is_first_live";
    public static final String SP_IS_FIRST_LIVE_REFUSE = "sp_is_first_live_refuse";
    public static final String SP_IS_FIRST_NEARBY = "sp_is_first_nearby";
    public static final String SP_IS_FIRST_REFUSE = "sp_is_first_refuse";
    public static final String SP_PLANT_HEAD_CLICK = "sp_plant_head_click";
    public static final String SP_PLANT_RANDOM_CLICK = "sp_plant_random_click";
    public static final String SP_SCAN_MISSIONS_CODE = "sp_scan_missions_code";
    public static final String SP_SEARCH_FRIEND_FIRST_SET = "sp_search_friend_first_set";
    public static final int START_LIVE_CODE = 10010;
    public static final String TEL_REGEX = "^((1[0-9]))\\d{9}$";
    public static final String TX_LIVE_APP_ID = "1256213697";
    public static final String TX_LIVE_UGC_KEY = "19ee5e6d456330e815dd45d9253fa0db";
    public static final String TX_UGC_LICENSE_URL = "https://license.vod2.myqcloud.com/license/v2/1256213697_1/v_cube.license";
    public static final String USER_SEARCH_NAME = "user_search_name";
    public static final String VIP_GOODS = "VIP_GOODS";
    public static final String WITHDRAWAL_CACHE = "withdrawal_cache";
    @Deprecated
    public static final int XM_CHINA_PUSH_BUZID = 21904;
    public static final int XM_CHINA_PUSH_BUZID_V2 = 25578;
    public static final String XM_PUSH_APPID = "2882303761517820134";
    public static final String XM_PUSH_APPKEY = "5811782057134";
    @Deprecated
    public static final int XM_PUSH_BUZID = 20924;
    public static final int XM_PUSH_EUROPE = 25575;
    public static final int XM_PUSH_INDIA = 25574;
    public static final int XM_PUSH_OTHER = 25577;
    public static final int XM_PUSH_RUSSIA = 25576;
    public static final Set<String> USER_SET = new ArraySet();
    public static final Set<String> SHOW_LOOK_SET = new ArraySet();
    public static final String URL_PAYONEER_CALL_BACK = x6.a.f59625a + "payoneer/notify/callback";
    public static int WITHDRAWAL_ALI_PAY = 1;
    public static int WITHDRAWAL_BANK_CARD = 2;
    public static int WITHDRAWAL_PAY_PAL = 3;
    public static int WITHDRAWAL_PAYONEER = 4;
    public static int WITHDRAWAL_USDT = 5;
    public static int WITHDRAWAL_PAYONEERV2 = 6;
    public static String WEI_BO_APP_KEY = "2754956957";
    public static String WEI_BO_REDIRECT_URL = "https://api.weibo.com/oauth2/default.html";
    public static String SCOPE = "email,direct_messages_read,direct_messages_write,friendships_groups_read,friendships_groups_write,statuses_to_me_read,follow_app_official_microblog,invitation_write";

    public static boolean isChinese() {
        return false;
    }
}
